### ISSUE TITLE
Some systems failed to build for Quicklisp dist

### ISSUE THREAD

**Issue by quicklisp** [mfiano/origin#8]
Building with SBCL 2.0.5 / ASDF 3.3.1 for quicklisp dist creation.

Trying to build commit id 138c0e49838f37e1147eb438da322a38c184b8fc

*net.mfiano.lisp.origin.test* fails to build because of a failure in  _net.mfiano.lisp.origin_.

*net.mfiano.lisp.origin* fails to build with the following error:

```
; caught ERROR:
;   READ error during COMPILE-FILE: Symbol "F32" not found in the NET.MFIANO.LISP.GOLDEN-UTILS package. Line: 131, Column: 36, File-Position: 1592 Stream: #<SB-INT:FORM-TRACKING-STREAM for "file /home/quicklisp/quicklisp-controller/dist/build-cache/origin/2c763f62ad0043f79c4330dfd35cb796e4757f89/origin-20201216-git/src/types/vec2.lisp" {1007198D93}>
...
Unhandled UIOP/LISP-BUILD:COMPILE-FILE-ERROR in thread #<SB-THREAD:THREAD "main thread" RUNNING {10008D8083}>: COMPILE-FILE-ERROR while compiling #<CL-SOURCE-FILE "net.mfiano.lisp.origin" "types" "vec2">

```

[Full log here](http://report.quicklisp.org/2020-12-16/failure-report/origin.html)

**Comment by mfiano** [comment]
Yes, I just hadn't pushed a recent commit for golden-utils until just now. Fixed.
